FROM node:16

# RUN mkdir -p /var/www/node

WORKDIR /var/www/node
# WORKDIR /usr/src/ap
# RUN echo pwd
# RUN echo ls

# COPY ../../../_proj/node/ .
# COPY package*.json ./

# RUN npm install

# COPY ${APP_CODE_PATH_HOST}/node/. .

# EXPOSE 9000

CMD ["node", "server.js"]